<?
use App\Models\Order;
use App\Models\OrderItem;

/**
* @var Order[] $orders
 */
?>
<html>
    <head>
        <title>Заказы</title>
        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <link rel="stylesheet" href="/css/bootstrap-theme.min.css">
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="/js/script.js"></script>
        <link rel="stylesheet" href="css/bootstrap-datetimepicker.min.css" />
        <script src="/js/moment-with-locales.min.js"></script>
        <script src="/js/bootstrap-datetimepicker.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="container theme-showcase">
            <div class="panel panel-default">
                <form action="/" method="get">
                    <table class="table">
                        <tr>
                            <td>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <label for="form_name">Дата от: *</label>
                                        <div class="form-group">
                                            <div class="input-group" id="datetimepicker1">
                                                <input name="data_from" type="text" class="form-control" value="<?= $this->request->getQuery("data_from") ?>"/>
                                                <span class="input-group-addon">
                                                    <i class="glyphicon glyphicon-calendar"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Инициализация Bootstrap DateTimePicker -->
                                    <script>
                                        $(function () {
                                            $('#datetimepicker1').datetimepicker({
                                                locale: 'ru'
                                            });
                                        });
                                    </script>
                                </div>
                            </td>
                            <td>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <label for="form_name">Цена от: *</label>
                                        <input name="price_from" type="text" class="form-control" value="<?= $this->request->getQuery("price_from") ?>" />
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <label for="name">Страна</label>
                                        <select name="country" class="form-control">
                                            <option value="">Не указано</option>
                                            <?php foreach ($customers as $customer) {?>
                                                <option <?=($this->request->getQuery("country") == $customer->cust_country)? 'selected' : ''?>><?=$customer->cust_country?></option>
                                            <?php }?>
                                        </select>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <label for="form_name">Дата до: *</label>
                                        <div class="form-group">
                                            <div class="input-group" id="datetimepicker2">
                                                <input name="data_to" type="text" class="form-control" value="<?= $this->request->getQuery("data_to") ?>"/>
                                                <span class="input-group-addon">
                                                    <i class="glyphicon glyphicon-calendar"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Инициализация Bootstrap DateTimePicker -->
                                    <script>
                                        $(function () {
                                            $('#datetimepicker2').datetimepicker({
                                                locale: 'ru'
                                            });
                                        });
                                    </script>
                                </div>
                            </td>
                            <td>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <label for="form_name">Цена до: *</label>
                                        <input name="price_to" type="text" class="form-control" value="<?= $this->request->getQuery("price_to") ?>" />
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <label for="name">Производитель</label>
                                        <select name="vend_name" class="form-control">
                                            <option value="">Не указано</option>
                                            <?php foreach ($vendors as $vendor) {?>
                                                <option <?=($this->request->getQuery("vend_name") == $vendor->vend_name)? 'selected' : ''?>><?=$vendor->vend_name?></option>
                                            <?php }?>
                                        </select>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <label for="name"></label>
                                        <button name="submit" type="submit" value="search" class="btn btn-default">Поиск</button>
                                        <a href="/" class="btn btn-default">Спросить</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
        <div class="container theme-showcase">
            <div class="panel panel-default">
                <div class="panel-heading">Заказы</div>
                <table class="table">
                    <tr>
                        <td>ИД заказа</td>
                        <td>Дата заказа</td>
                        <td>Общая сумма заказа</td>
                        <td>Количество продуктов заказа</td>
                    </tr>
                    <?php if(count($page->items) == 0){?>
                        <tr>
                            <td colspan="4">
                                По данном запросу ничего не найдено. Попробуйте изменить фильтр.
                            </td>
                        </tr>
                    <?php }else{ ?>
                        <?php foreach ($page->items as $order) {?>
                            <tr>
                                <td><?= $order->order_num ?></td>
                                <td><?= $order->order_date ?></td>
                                <td><?= $order->sum ?></td>
                                <td><?= $order->count ?> <a data-id="<?= $order->order_num ?>" class="btn btn-default getAllData">Посмотреть</a></td>
                            </tr>
                        <?php }?>
                    <?php } ?>

                </table>
            </div>
            <?php if($page->total_pages > '1'){?>
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <?php if($page->current != 1){?>
                            <li class="page-item">
                                <a class="page-link" href="<?= $current_url ?>" aria-label="Первая">
                                    <span aria-hidden="true">Первая</span>
                                </a>
                            </li>

                            <li class="page-item">
                                <a class="page-link" href="<?= $current_url ?>&page=<?= $page->before; ?>" aria-label="Предыдущая">
                                    <span aria-hidden="true">   &laquo;   </span>
                                </a>
                            </li>
                        <?php }?>

                        <li class="page-item">
                            <a class="page-link">
                                <span aria-hidden="true">Вы на <?= $page->current ?> странице из <?= $page->total_pages ?></span>
                            </a>
                        </li>

                        <?php if($page->current != $page->total_pages){?>
                            <li class="page-item">
                                <a class="page-link" href="<?= $current_url ?>&page=<?= $page->next; ?>" aria-label="Следующая">
                                    <span aria-hidden="true">   &raquo;   </span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="<?= $current_url ?>&page=<?= $page->last; ?>" aria-label="Последняя">
                                    <span aria-hidden="true">Последняя</span>
                                </a>
                            </li>
                        <?php }?>
                    </ul>
                </nav>
            <?php }?>
        </div>

        <div id="detailOrder" class="modal fade">
            <div class="modal-dialog" style="width: 80%;">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title">Детальное описание заказа №<span class="order_nomer"></span> </h4>
                    </div>
                    <div class="modal-body">
                        <table class="table content_table">
                            <tr>
                                <td>ИД продукта</td>
                                <td>Название</td>
                                <td>Стоимость за шт</td>
                                <td>Колличество</td>
                                <td>Итоговая сумма</td>
                            </tr>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>